apiVersion: v1
kind: PersistentVolume
metadata:
  name: msql-pv
spec:
  capacity:
    storage: 200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain 
  storageClassName: standard
  nfs:
    path: /some/path
    server: 1.2.3.4